# fly.toml app configuration file generated for agentic-devops on 2025-03-21T18:07:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agentic-devops'
primary_region = 'lax'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
